Build sp vm
Super-Protocol/sp-vm pull request #1
Opened 2024-10-01 19:34 UTC by Villain88

2024-10-01 20:02 UTC, AgentRX requested changes

2024-10-01 20:02 UTC, AgentRX commented on .github/workflows/build-sp-vm.yml
> +          patch=$((patch + 1))
Shoud we use github.run_id here?

2024-10-02 10:52 UTC, Villain88 commented on .github/workflows/build-sp-vm.yml
> +          patch=$((patch + 1))
done

2024-10-02 10:55 UTC, AgentRX approved these changes

2024-10-03 08:53 UTC, merged